-- MySQL Script generated by MySQL Workbench
-- Thu Nov  6 16:14:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_res_manga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_res_manga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_res_manga` DEFAULT CHARACTER SET utf8 ;
USE `bd_res_manga` ;

-- -----------------------------------------------------
-- Table `bd_res_manga`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(255) NOT NULL,
  `usuario_data_nasc` DATE NOT NULL,
  `usuario_email` VARCHAR(255) NOT NULL,
  `usuario_senha` VARCHAR(255) NOT NULL,
  `usuario_foto` VARCHAR(255) NULL,
  `usuario_tipo` CHAR(5) NOT NULL DEFAULT 'comun',
  `usuario_nick` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_email_UNIQUE` (`usuario_email` ASC) VISIBLE,
  UNIQUE INDEX `usuario_nick_UNIQUE` (`usuario_nick` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`autor` (
  `autor_id` INT NOT NULL AUTO_INCREMENT,
  `autor_nome` VARCHAR(255) NOT NULL,
  `autor_data_nasc` VARCHAR(45) NOT NULL,
  `autor_data_morte` VARCHAR(45) NULL,
  `autor_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`autor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`obra` (
  `obra_id` INT NOT NULL AUTO_INCREMENT,
  `obra_nome` VARCHAR(255) NOT NULL,
  `obra_data_inicio` VARCHAR(45) NOT NULL,
  `obra_data_final` VARCHAR(45) NULL,
  `obra_qtd_capitulos` INT NOT NULL,
  `obra_qtd_volumes` INT NULL,
  `obra_autor_id` INT NOT NULL,
  `obra_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`obra_id`),
  INDEX `fk_obra_autor1_idx` (`obra_autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_obra_autor1`
    FOREIGN KEY (`obra_autor_id`)
    REFERENCES `bd_res_manga`.`autor` (`autor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`resenha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`resenha` (
  `resenha_id` INT NOT NULL AUTO_INCREMENT,
  `resenha_titulo` VARCHAR(100) NOT NULL,
  `resenha_data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resenha_conteudo` TEXT NOT NULL,
  `resenha_usuario_id` INT NOT NULL,
  `resenha_obra_id` INT NOT NULL,
  PRIMARY KEY (`resenha_id`),
  INDEX `fk_resenha_usuario1_idx` (`resenha_usuario_id` ASC) VISIBLE,
  INDEX `fk_resenha_obra1_idx` (`resenha_obra_id` ASC) VISIBLE,
  CONSTRAINT `fk_resenha_usuario1`
    FOREIGN KEY (`resenha_usuario_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resenha_obra1`
    FOREIGN KEY (`resenha_obra_id`)
    REFERENCES `bd_res_manga`.`obra` (`obra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`favorito` (
  `favorito_usuario_id` INT NOT NULL,
  `favorito_tipo` CHAR(2) NOT NULL,
  `favorito_id` INT NOT NULL,
  INDEX `fk_favorito_usuario1_idx` (`favorito_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`favorito_usuario_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`likes` (
  `likes_usuario_id` INT NOT NULL,
  `likes_resenha_id` INT NOT NULL,
  PRIMARY KEY (`likes_usuario_id`, `likes_resenha_id`),
  INDEX `fk_like_resenha1_idx` (`likes_resenha_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_usuario1`
    FOREIGN KEY (`likes_usuario_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_resenha1`
    FOREIGN KEY (`likes_resenha_id`)
    REFERENCES `bd_res_manga`.`resenha` (`resenha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
