-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 13:16:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_res_manga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_res_manga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_res_manga` DEFAULT CHARACTER SET utf8 ;
USE `bd_res_manga` ;

-- -----------------------------------------------------
-- Table `bd_res_manga`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(45) NOT NULL,
  `usuario_data_nasc` DATE NOT NULL,
  `usuario_email` VARCHAR(45) NOT NULL,
  `usuario_senha` VARCHAR(45) NOT NULL,
  `usuario_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`autor` (
  `autor_id` INT NOT NULL AUTO_INCREMENT,
  `autor_nome` VARCHAR(45) NOT NULL,
  `autor_data_nasc` VARCHAR(45) NOT NULL,
  `autor_data_morte` VARCHAR(45) NULL,
  `autor_foto` VARCHAR(255) NULL,
  PRIMARY KEY (`autor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`obra` (
  `obra_id` INT NOT NULL AUTO_INCREMENT,
  `obra_nome` VARCHAR(45) NOT NULL,
  `obra_data_inicio` VARCHAR(45) NOT NULL,
  `obra_data_final` VARCHAR(45) NULL,
  `obra_qtd_capitulos` INT NULL,
  `obra_qtd_volumes` VARCHAR(45) NOT NULL,
  `obra_autor` INT NOT NULL,
  PRIMARY KEY (`obra_id`, `obra_autor`),
  INDEX `fk_obra_autor1_idx` (`obra_autor` ASC) VISIBLE,
  CONSTRAINT `fk_obra_autor1`
    FOREIGN KEY (`obra_autor`)
    REFERENCES `bd_res_manga`.`autor` (`autor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`resenha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`resenha` (
  `resenha_id` INT NOT NULL AUTO_INCREMENT,
  `resenha_titulo` VARCHAR(45) NOT NULL,
  `resenha_data` VARCHAR(45) NOT NULL,
  `resenha_conteudo` TEXT(800) NOT NULL,
  `resenha_resenhista` INT NOT NULL,
  `resenha_obra` INT NOT NULL,
  PRIMARY KEY (`resenha_id`, `resenha_resenhista`, `resenha_obra`),
  INDEX `fk_resenha_usuario_idx` (`resenha_resenhista` ASC) VISIBLE,
  INDEX `fk_resenha_obra1_idx` (`resenha_obra` ASC) VISIBLE,
  CONSTRAINT `fk_resenha_usuario`
    FOREIGN KEY (`resenha_resenhista`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resenha_obra1`
    FOREIGN KEY (`resenha_obra`)
    REFERENCES `bd_res_manga`.`obra` (`obra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`favorito` (
  `favorito_usuario_id` INT NOT NULL,
  `favorito_obra_id` INT NOT NULL,
  `favorito_autor_id` INT NOT NULL,
  `favorito_resenhista_id` INT NOT NULL,
  PRIMARY KEY (`favorito_usuario_id`),
  INDEX `fk_favorito_obra1_idx` (`favorito_obra_id` ASC) VISIBLE,
  INDEX `fk_favorito_autor1_idx` (`favorito_autor_id` ASC) VISIBLE,
  INDEX `fk_favorito_usuario2_idx` (`favorito_resenhista_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorito_usuario1`
    FOREIGN KEY (`favorito_usuario_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_obra1`
    FOREIGN KEY (`favorito_obra_id`)
    REFERENCES `bd_res_manga`.`obra` (`obra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_autor1`
    FOREIGN KEY (`favorito_autor_id`)
    REFERENCES `bd_res_manga`.`autor` (`autor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorito_usuario2`
    FOREIGN KEY (`favorito_resenhista_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_res_manga`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_res_manga`.`like` (
  `obra_usuario_id` INT NOT NULL,
  `obra_resenha_id` INT NOT NULL,
  PRIMARY KEY (`obra_usuario_id`, `obra_resenha_id`),
  INDEX `fk_like_resenha1_idx` (`obra_resenha_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_usuario1`
    FOREIGN KEY (`obra_usuario_id`)
    REFERENCES `bd_res_manga`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_resenha1`
    FOREIGN KEY (`obra_resenha_id`)
    REFERENCES `bd_res_manga`.`resenha` (`resenha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
